In [1]:
import numpy as np

A = np.array(((1,-1,1/np.sqrt(6)), (0,1,1/np.sqrt(6)), (1,0,-1/np.sqrt(6))))
P = np.identity(3)- (1/3)*np.array(((1,-2,-1), (-2,4,2), (-1,2,1)))

In [22]:
import scipy.linalg as spla

In [23]:
np.dot(P,A)

array([[ 3.00000000e+00, -2.22044605e-16,  1.20000000e+01],
       [ 1.11022302e-16, -3.00000000e+00,  1.20000000e+01],
       [ 1.11022302e-16,  2.22044605e-16,  6.00000000e+00]])

In [43]:
A = np.array(((0,1),(1,1), (1,0)))
b = np.array((1,2,-1))

In [44]:
np.dot(np.linalg.pinv(A,),b)

array([-0.33333333,  1.66666667])

In [2]:
U,s,Vt = np.linalg.svd(A)

In [5]:
s

array([1.73205081, 1.        , 0.70710678])

In [42]:
np.dot(A,np.array((-1/3,5/3)))

array([ 1.66666667,  1.66666667, -0.33333333])

In [45]:
A = np.array(((1,0), (-1,1)))

In [48]:
np.linalg.inv(A)

array([[1., 0.],
       [1., 1.]])